### ISSUE TITLE
[!] Release Flags for a Trojan file, on Windows Defender [!]

### ISSUE THREAD

**Issue by ohsevin** [wheybags/EmperorLauncher#1]
https://github.com/wheybags/EmperorLauncher/releases/download/v1.0/EmperorLauncher.v1.0.zip

=

/!\ TROJAN (Source: Windows Defender)

**Comment by ohsevin** [comment]
![v1](https://github.com/user-attachments/assets/ab98d500-e221-4cde-b193-5bd13d188007)

**Comment by wheybags** [comment]
Yep, the things this program is doing look a lot like malware (detouring system DLLs). Not much I can do about this - I'm not gonna buy a codesigning key to make it go away. If you still feel uncomfortable, feel free to audit the source code and then build it yourself, unfortunately that's all I can offer :(
