### ISSUE TITLE
Detected Trojan:AndroidOS/ZkarletFlash

### ISSUE THREAD

**Issue by chrisregistered2022** [wheybags/EmperorLauncher#11]
Firefox and Windows Security identify EmperorLauncher.v1.0 as containing a trojan, Trojan:AndroidOS/ZkarletFlash, 
Alert level: Severe
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Is this a false positive due to application hooks required to make Emperor compatible with Windows 11? Is it possible to fix this and recompile so it doesn't come up as a trojan? Thank you!

**Comment by wheybags** [comment]
Yes, it's a false positive, no it's not possible to fix it unfortunately,  see #1
