### ISSUE TITLE
Launch fails with assert failed: DetourCreateProcessWithDllA

### ISSUE THREAD

**Issue by Vegasq** [wheybags/EmperorLauncher#2]
# Steps

1. Grabbed 4 iso files and install the game. It seems version is 1.04.
2. Install patch 1.09
3. Copy crack (Emperor.exe 948,743 bytes) without it game refuses to start at all. With it game starts and reports 1.09
4. Copy the Launcher and it's dll into the game folder.
5. Open the Launcher and press Play.

# Error

assert failed: DetourCreateProcessWithDllA

![image](https://github.com/user-attachments/assets/ab1f5bc0-1f33-40be-8342-fcf9c3bd988a)

**Comment by wheybags** [comment]
Yes, that is not the correct procedure to use this patch. You don't use the original installer, just extract the patch exe and dll into an empty folder and it will build its own install folder directly from the cds.
