### ISSUE TITLE
Windows automatically deletes EmperorLauncher.v1.0.zip since it gets detected as a virus

### ISSUE THREAD

**Issue by aqocyrale** [wheybags/EmperorLauncher#3]
Windows automatically deletes EmperorLauncher.v1.0.zip since it gets detected as a virus.
While I understand on a technical level that the nature of DLL hooking and function overrides that this is doing is what's causing it, it makes it hard to just send a release to friends I want to play emperor with and ask them to play together.

Imagine if somebody messages you on discord out of the blue and goes "hey, come play this game with me" and sends you a zip with an exe that gets auto detected as a virus by windows. yeah. yikes.

I'm not sure how interested you are in this project at this point, it seems like you met your original goals with IDA reverse engineering practice based on reading your post at wheybags.com/blog/emperor.html, but do you think at any point in the future you would be interested in trying to get around this issue? Maybe it's possible to just package a single prepatched binary without needing any hooking? I don't know, I'm not an expert on this myself.

I do appreciate your desire to keep emperor playable for everyone forever, and I wonder if you have a full writeup of a knowledge dump allowing someone else to learn about your journey with this on a more detailed technical level, and then potential continue your work.

Either way, thanks a lot for making this! I grew up on Dune RTSs, and they're also what got me into programming. It's really cool to see this. you're the best

**Comment by wheybags** [comment]
Hey, thanks for the interest!
Unfortunately there's not much I can do about this. It could be worked around if I bought a windows code signing key and signed the binaries, but that's not something I want to get into for this project.

Maybe if enough people report false positives somewhere it would go away, I don't know. In the meantime all you can do is either unquarantine it, or disable windows defender completely.

**Comment by aqocyrale** [comment]
Well, I have no problem getting around this myself; the main problem lies in sending this to other people and getting them to trust me that this is actually something they can use to play a game and not just a scam to hack their computer by someone who took over my account and is pretending to be me.

I wonder if using UPX can get around the issue... or maybe an implementation in a non-C programming language that uses an existing exe that is already signed, e.g. such as electron. it's bloated but it might avoid the security warning.

(p.s. I just realized why your name looked familiar, you worked on factorio! holyyy. you're a legend)
