### ISSUE TITLE
Wine: failure to launch game

### ISSUE THREAD

**Issue by stefantalpalaru** [wheybags/EmperorLauncher#4]
While running it from Linux, under Wine/Proton/Proton-GE, I get this error after clicking "Play":

```text
wine: Call from 7BF61B58 to unimplemented function OLEAUT32.dll.444, aborting
wine client error:1c0: Initial process has exited (return code: 256)
```

The installation worked without any glitch.

**Comment by wheybags** [comment]
Sorry, I'm afraid I'm not going to work on supporting wine.
