### ISSUE TITLE
Faild to start on linux (wine)

### ISSUE THREAD

**Issue by axet** [wheybags/EmperorLauncher#7]
Hello!

Launcher failed to start the game under linux under wine.

1) Installer works into Z:/data
2) Game failed to start with different errors.

Sometimes:

1) sometimes unimplemented Ole32.dll method:

```
wine: Call from 7BD2D088 to unimplemented function OLEAUT32.dll.444, aborting
wine: Unimplemented function OLEAUT32.dll.444 called at address 7BD2D088 (thread 011c), starting debugger...
WineDbg attached to pid 0000
wine: Call from 7BD2D088 to unimplemented function OLEAUT32.dll.444, aborting
```

2) failed to DetourCreateProcess 

![Screenshot from 2024-09-04 13-22-09](https://github.com/user-attachments/assets/e2eabfa0-d71d-4e63-abde-2d2590135e5d)

**Comment by wheybags** [comment]
Sorry, wine is not supported
