### ISSUE TITLE
Make it run using ASI scripts

### ISSUE THREAD

**Issue by tigrik2017** [wheybags/EmperorLauncher#9]
Not an issue but a proposal or question

Is there a way to use this using ASI scripts? I've already found a working way to use ASI injector, but had some difficulties with reverse engineering to apply all the fixes are needed. If I'm not mistaken -- I've used injector via binkview.dll and succesfully run console on game run with showing some data.

Also, if I'm not mistaken, I can use all the hooks (or at least paritally) from your project to make it working on existing installation via ASI instead of installing the game again via launcher? Theoretically, in the end it should work with all versions of the game (meanin language versions, not version of the game itself).

**Comment by wheybags** [comment]
I haven't heard of asi before, but looking it up it seems to be some sort of library or toolkit for injecting code patches into a game process? I would guess this project could probably be implemented like that, but that's not the way I did it, and I'm not going to put in the work to port it.

As for different language versions - I may be wrong, but I think there is a different game.exe for each language, so I think some of the work of making patches would need to be redone for each language. I'm also not personally interested in doing this, but if someone else is and sends me a patch, I'd be happy to accept it.
